const SCHEMA = [
  {
    id: "/source_index",
    source: "/index",
    key: "source",
  },
  {
    id: "/parent_index",
    source: "/index",
    key: "parent_id",
  },
  {
    id: "/deck_id_index",
    source: "/index",
    key: "deck_id",
  },
  {
    id: "/card_id_index",
    source: "/index",
    key: "card_id",
  },
  {
    id: "/forward_subscription",
    source: "/subscription",
    key: "source",
    event: "/forwarded",
    event_source: "/card",
    command: "/detail",
    unique_key: "id",
  },
  {
    id: "/back_subscription",
    source: "/subscription",
    key: "source",
    event: "/backed",
    event_source: "/card",
    command: "/detail",
    unique_key: "id",
  },
  {
    id: "/flip_subscription",
    source: "/subscription",
    key: "source",
    event: "/flipped",
    event_source: "/card",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/reverse_subscription",
    source: "/subscription",
    key: "source",
    event: "/reversed",
    event_source: "/card",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/draw_subscription",
    source: "/subscription",
    key: "source",
    event: "/drawn",
    event_source: "/deck",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/replace_subscription",
    source: "/subscription",
    key: "source",
    event: "/replaced",
    event_source: "/deck",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/initial_load_subscription",
    source: "/subscription",
    key: "source",
    event: "/loaded",
    event_source: "/app",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/app_outline_screen_outline",
    source: "/subscription",
    event: "/entered",
    event_source: "/card",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/card_outline_detail",
    source: "/subscription",
    event: "/outlined",
    event_source: "/card",
    command: "/detail",
    unique_key: "id",
  },
  {
    id: "/deck_outline_detail",
    source: "/subscription",
    event: "/outlined",
    event_source: "/deck",
    command: "/detail",
    unique_key: "id",
  }
];
const EXPECTATION_0 = [];
const EXPECTATION_1 = [];
const EXPECTATION_2 = [];
const EXPECTATION_3 = [];
