const MISENPLACE_SCHEMA = [{
  application: "/virgil",
  source: "/subscription",
}];

const SCHEMA = [
  {
    id: "/deck_id_index",
    source: "/index",
    key: "deck_id",
  },
  {
    id: "/initialize_subscription",
    source: "/subscription",
    key: "source",
    event: "/load",
    event_source: "/misenplace/app",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/outline_detail_app_subscription",
    source: "/subscription",
    key: "source",
    event: "/outline",
    event_source: "/misenplace/app",
    command: "/detail",
    unique_key: "id",
  },
];

const NAVIGATION_SUBSCRIPTIONS = [
  {
    id: "/forward_subscription",
    source: "/subscription",
    key: "source",
    event: "/forwarded",
    event_source: "/card",
    command: "/detail",
    unique_key: "id",
  },
  {
    id: "/back_subscription",
    source: "/subscription",
    key: "source",
    event: "/backed",
    event_source: "/card",
    command: "/detail",
    unique_key: "id",
  },
  {
    id: "/flip_subscription",
    source: "/subscription",
    key: "source",
    event: "/flipped",
    event_source: "/card",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/reverse_subscription",
    source: "/subscription",
    key: "source",
    event: "/reversed",
    event_source: "/card",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/draw_subscription",
    source: "/subscription",
    key: "source",
    event: "/drawn",
    event_source: "/deck",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/replace_subscription",
    source: "/subscription",
    key: "source",
    event: "/replaced",
    event_source: "/deck",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/initial_load_subscription",
    source: "/subscription",
    key: "source",
    event: "/loaded",
    event_source: "/app",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/app_outline_screen_outline",
    source: "/subscription",
    event: "/entered",
    event_source: "/card",
    command: "/outline",
    unique_key: "id",
  },
  {
    id: "/card_outline_detail",
    source: "/subscription",
    event: "/outlined",
    event_source: "/card",
    command: "/detail",
    unique_key: "id",
  },
];
