[
  {
    source: "/procedure/subscription",
    procedure: "/html",
    event: "/navigate/next",
    action: HTML.detail,
    reaction: HTML.transition,
  },
  {
    source: "/procedure/subscription",
    procedure: "/html",
    event: "/navigate/forward",
    action: HTML.detail,
    reaction: HTML.transition,
  },
  {
    source: "/procedure/subscription",
    procedure: "/html",
    event: "/navigate/flip",
    action: HTML.outline,
    reaction: HTML.transition,
  },
  {
    source: "/procedure/subscription",
    procedure: "/html",
    event: "/navigate/draw",
    action: HTML.outline,
    reaction: HTML.transition,
  },
  {
    source: "/procedure/subscription",
    procedure: "/html",
    event: "/navigate/previous",
    action: HTML.detail,
    reaction: HTML.transition,
  },
  {
    source: "/procedure/subscription",
    procedure: "/html",
    event: "/navigate/back",
    action: HTML.detail,
    reaction: HTML.transition,
  },
  {
    source: "/procedure/subscription",
    procedure: "/html",
    event: "/navigate/reverse",
    action: HTML.outline,
    reaction: HTML.transition,
  },
  {
    source: "/procedure/subscription",
    procedure: "/html",
    event: "/navigate/replace",
    action: HTML.outline,
    reaction: HTML.transition,
  },
].forEach((c) => PROCESS.model.set(c));
