COMPONENTS.push(
  ...[
    {
      source: "/procedure/subscription",
      procedure: "/navigation",
      event: "/message/next",
      action: (model, message, resultId) => {},
      reaction: (model, message, resultId) => {},
    },
    {
      source: "/procedure/subscription",
      procedure: "/navigation",
      event: "/message/previous",
      action: (model, message, resultId) => {},
      reaction: (model, message, resultId) => {},
    },
    {
      source: "/procedure/subscription",
      procedure: "/navigation",
      event: "/message/forward",
      action: (model, message, resultId) => {},
      reaction: (model, message, resultId) => {},
    },
    {
      source: "/procedure/subscription",
      procedure: "/navigation",
      event: "/message/back",
      action: (model, message, resultId) => {},
      reaction: (model, message, resultId) => {},
    },
    {
      source: "/procedure/subscription",
      procedure: "/navigation",
      event: "/message/flip",
      action: (model, message, resultId) => {},
      reaction: (model, message, resultId) => {},
    },
    {
      source: "/procedure/subscription",
      procedure: "/navigation",
      event: "/message/reverse",
      action: (model, message, resultId) => {},
      reaction: (model, message, resultId) => {},
    },
    {
      source: "/procedure/subscription",
      procedure: "/navigation",
      event: "/user_input/draw",
      result: "/message/draw",
      action: (model, message, resultId) => {},
      reaction: (model, message, resultId) => {},
    },
    {
      source: "/procedure/subscription",
      procedure: "/navigation",
      event: "/user_input/replace",
      result: "/message/replace",
      action: (model, message, resultId) => {},
      reaction: (model, message, resultId) => {},
    },
  ],
);
